/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in real projects. It is committed here so
// TypeScript understands the app before dependencies are installed.
