import { readFile } from "node:fs/promises";

const defaultBaseUrl = "http://127.0.0.1:3070";
const demoDataUrl = new URL("../../../packages/shared/demo-data/asts-demo.json", import.meta.url);
const demoData = JSON.parse(await readFile(demoDataUrl, "utf8"));
const preWinTenders = demoData.tenders.filter((tender) => tender.funnel === "pre_win");
const executionTenders = demoData.tenders.filter((tender) => tender.funnel === "execution");
const executionDocuments = demoData.documents.filter((document) =>
  executionTenders.some((tender) => tender.tender_id === document.tender_id),
);
const preWinOutcomeCounts = ["suggested", "locked", "approved"]
  .map((outcome) => preWinTenders.filter((tender) => tender.outcome.status === outcome).length)
  .join("/");
const fixtureDriftCheckCount = 4;
const approvedPreWinTender = preWinTenders.find((tender) => tender.outcome.status === "approved");
const lockedPreWinTender = preWinTenders.find((tender) => tender.outcome.status === "locked");

if (!approvedPreWinTender) {
  throw new Error("demo fixture must include approved pre-win owner receipt");
}

if (!lockedPreWinTender) {
  throw new Error("demo fixture must include locked pre-win quarantine source");
}

function htmlAttributeValue(value) {
  return value.replaceAll("&", "&amp;");
}

const tenderDetailRouteChecks = preWinTenders.map((tender) => ({
  path: `/tenders/${tender.tender_id}`,
  status: 200,
  mustInclude: [
    "Карточка процедуры",
    "Outcome / reason",
    "Source-id mismatch hint",
    "tender_id / regNumber",
    "raw artifact нужен только как evidence",
    "Primary source deep link",
    "data-testid=\"source-url-deep-link\"",
    `data-source-url="${htmlAttributeValue(tender.source.source_url)}"`,
    `href="${htmlAttributeValue(tender.source.source_url)}"`,
    "Открыть первоисточник",
    tender.title,
    tender.outcome.owner_role,
    tender.outcome.source_ref,
    tender.source.raw_artifact_id,
  ],
}));

const outcomeFilterRouteChecks = ["suggested", "locked", "approved"].map((outcome) => {
  const tender = preWinTenders.find((item) => item.outcome.status === outcome);
  const visibleCount = preWinTenders.filter((item) => item.outcome.status === outcome).length;

  if (!tender) {
    throw new Error(`demo fixture must include pre-win outcome ${outcome}`);
  }

  return {
    path: `/tenders?outcome=${outcome}`,
    status: 200,
    mustInclude: [
      "Outcome filters",
      "Owner approval receipt",
      "data-testid=\"owner-approval-browser-loop\"",
      `data-active-outcome="${outcome}"`,
      `data-visible-count="${visibleCount}"`,
      outcome,
      tender.tender_id,
      tender.title,
      tender.outcome.note,
    ],
  };
});

const executionDocumentMarkers = executionTenders.flatMap((tender) =>
  demoData.documents
    .filter((document) => document.tender_id === tender.tender_id)
    .flatMap((document) => [document.title, document.raw_artifact.artifact_id, document.raw_artifact.storage_path]),
);

const routeChecks = [
  {
    path: "/",
    status: 200,
    mustInclude: [
      "Рабочий кабинет тендерного отдела",
      "Поставка серверного оборудования для регионального центра",
      "0373100042626000001",
      "Воронка 1: до победы",
      "Воронка 2: исполнение",
      "Bitrix24",
      "19 static routes",
    ],
  },
  {
    path: "/plan",
    status: 200,
    mustInclude: [
      "План разработки ASTS",
      "80-point plan",
      "Next increments",
      "Добавить source owner receipt write API draft",
      "Добавить AI review receipt write API draft",
      "Добавить source freshness write API draft",
      "Добавить EIS real-network approval API copy",
      "Schema validation summary",
      "data-testid=\"schema-validation-summary-card\"",
      "data-check-count=\"14\"",
      "data-schema-count=\"3\"",
      "data-testid=\"schema-docs-link\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/packages/shared/README.md#shared-schema-index\"",
      "href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/packages/shared/README.md#shared-schema-index\"",
      "Shared schema index",
      "source-owner-receipts.schema.json",
      "fns-connector-gate.schema.json",
      "ai-review-queue.schema.json",
      "Shared validation browser loop",
      "data-testid=\"shared-validation-browser-loop\"",
      "data-check-count=\"14\"",
      "data-workflow=\"Shared validation\"",
      "data-command=\"cd packages/shared &amp;&amp; npm run validate\"",
      "data-ci-paths=\"packages/shared/**,docs/19-continuation-70-step-plan-ru.md,.github/workflows/shared-validation.yml\"",
      "data-selector=\"[data-testid=&#x27;schema-validation-summary-card&#x27;] [data-schema-id]\"",
      "shared checks",
      "packages/shared/**",
      "docs/19-continuation-70-step-plan-ru.md",
      ".github/workflows/shared-validation.yml",
      "npm run validate",
      "Shared validation CI badge link",
      "data-testid=\"shared-validation-ci-badge-link\"",
      "data-badge-label=\"Shared validation\"",
      "data-workflow-name=\"Shared validation\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/shared-validation.yml\"",
      "data-pr-gate-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/shared-validation.yml\"",
      "data-browser-loop-selector=\"[data-testid=&#x27;shared-validation-browser-loop&#x27;]\"",
      "data-ci-path=\".github/workflows/shared-validation.yml\"",
      "data-command=\"cd packages/shared &amp;&amp; npm run validate\"",
      "Shared validation workflow",
      "browser loop связан с GitHub Actions",
      "Shared validation workflow file smoke",
      "data-testid=\"shared-validation-workflow-file-smoke\"",
      "data-workflow-path=\".github/workflows/shared-validation.yml\"",
      "data-workflow-name=\"Shared validation\"",
      "data-working-directory=\"packages/shared\"",
      "data-node-version=\"22\"",
      "data-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:shared-validation-workflow\"",
      "data-expected-paths=\"packages/shared/**,docs/19-continuation-70-step-plan-ru.md,.github/workflows/shared-validation.yml\"",
      "Как `/plan` сверяет реальный GitHub Actions файл",
      "Validate step выполняет npm run validate",
      "Shared validation workflow CI note",
      "data-testid=\"shared-validation-workflow-ci-note\"",
      "data-command=\"npm run smoke:shared-validation-workflow\"",
      "data-source-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:shared-validation-workflow\"",
      "data-file-smoke-selector=\"[data-testid=&#x27;shared-validation-workflow-file-smoke&#x27;]\"",
      "data-checked-workflow-name=\"Shared validation\"",
      "data-checked-workflow-path=\".github/workflows/shared-validation.yml\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как workflow file smoke входит в Web build",
      "Web build запускает workflow file smoke до route smoke",
      "Shared validation workflow step smoke",
      "data-testid=\"shared-validation-workflow-step-smoke\"",
      "data-command=\"npm run smoke:shared-validation-workflow-step\"",
      "data-source-smoke-command=\"npm run smoke:shared-validation-workflow\"",
      "data-file-smoke-selector=\"[data-testid=&#x27;shared-validation-workflow-file-smoke&#x27;]\"",
      "data-source-ci-note-selector=\"[data-testid=&#x27;shared-validation-workflow-ci-note&#x27;]\"",
      "data-checked-workflow-name=\"Shared validation\"",
      "data-checked-workflow-path=\".github/workflows/shared-validation.yml\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как Shared validation note сверяется с Web build",
      "Web build запускает smoke:shared-validation-workflow-step до route smoke",
      "Shared validation workflow failure copy",
      "data-testid=\"shared-validation-workflow-failure-copy\"",
      "data-command=\"npm run smoke:shared-validation-workflow-failure-copy\"",
      "data-failing-command=\"npm run smoke:shared-validation-workflow-step\"",
      "data-no-merge-copy=\"Не мержить, пока .github/workflows/web-build.yml снова запускает shared validation workflow smoke и step smoke в правильном порядке\"",
      "data-owner-role=\"Schema owner + CI owner\"",
      "data-repair-targets=\".github/workflows/web-build.yml,.github/workflows/shared-validation.yml,/plan,[data-testid=&#x27;shared-validation-workflow-step-smoke&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;shared-validation-workflow-step-smoke&#x27;]\"",
      "Что делать, если shared validation workflow упал",
      "не мержить, пока shared validation workflow smoke и step smoke снова не зеленые",
      "Shared validation live route gate note",
      "data-testid=\"shared-validation-live-route-gate-note\"",
      "data-browser-loop-selector=\"[data-testid=&#x27;shared-validation-browser-loop&#x27;]\"",
      "data-checked-workflow-path=\".github/workflows/shared-validation.yml\"",
      "data-check-count=\"14\"",
      "data-command=\"npm run smoke:shared-validation-live-route\"",
      "data-marker-selector=\"[data-testid=&#x27;shared-validation-workflow-step-smoke&#x27;]\"",
      "data-route-smoke-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-source-smoke-command=\"npm run smoke:shared-validation-workflow-step\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как live route smoke защищает shared validation",
      "затем route smoke проверяет `/plan` shared validation markers на живом сервере",
      "Shared validation failure copy",
      "data-testid=\"shared-validation-failure-copy\"",
      "data-command=\"npm run smoke:shared-validation-failure-copy\"",
      "data-failing-command=\"npm run smoke:shared-validation-live-route\"",
      "data-no-merge-copy=\"Не мержить, пока `/plan`, packages/shared/** и .github/workflows/shared-validation.yml снова не проходят 14 shared checks\"",
      "data-owner-role=\"Schema owner + CI owner\"",
      "data-repair-targets=\"/plan,packages/shared/**,.github/workflows/shared-validation.yml,docs/19-continuation-70-step-plan-ru.md\"",
      "data-source-marker-selector=\"[data-testid=&#x27;shared-validation-live-route-gate-note&#x27;]\"",
      "Что делать, если shared validation drift упал",
      "не мержить, пока shared validation smoke и route smoke снова не зеленые",
      "Shared validation rendered-route failure copy",
      "data-testid=\"shared-validation-rendered-route-failure-copy\"",
      "data-command=\"npm run smoke:shared-validation-rendered-route-failure-copy\"",
      "data-check-count=\"14\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова покрывает shared validation markers на живом `/plan`\"",
      "data-owner-role=\"Schema owner + QA owner\"",
      "data-repair-targets=\"apps/web/scripts/smoke.mjs,apps/web/app/plan/page.tsx,packages/shared/**,/plan,[data-testid=&#x27;shared-validation-failure-copy&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;shared-validation-failure-copy&#x27;]\"",
      "Что делать, если shared validation пропала в rendered routes",
      "не мержить, пока shared validation markers снова не проходят rendered routes smoke",
      "Fixture schema checklist smoke",
      "data-testid=\"fixture-schema-checklist-smoke\"",
      "data-schema-count=\"5\"",
      "data-command-count=\"4\"",
      "data-readme-anchor=\"packages/shared/README.md#shared-schema-index\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "ai-schemas/tender-position-extraction.schema.json",
      "ai-schemas/supplier-quote-normalization.schema.json",
      "fixture-schemas/source-owner-receipts.schema.json",
      "fixture-schemas/fns-connector-gate.schema.json",
      "fixture-schemas/ai-review-queue.schema.json",
      "data-commands=\"cd packages/shared &amp;&amp; npm run validate | cd apps/web &amp;&amp; npm run smoke:owner-receipts | cd apps/web &amp;&amp; npm run smoke:fns-approvals | cd apps/web &amp;&amp; npm run smoke:ai-review-actions\"",
      "cd packages/shared &amp;&amp; npm run validate",
      "cd apps/web &amp;&amp; npm run smoke:owner-receipts",
      "cd apps/web &amp;&amp; npm run smoke:fns-approvals",
      "cd apps/web &amp;&amp; npm run smoke:ai-review-actions",
      "Shared README command parity smoke",
      "data-testid=\"shared-readme-command-parity-smoke\"",
      "data-checklist-selector=\"[data-testid=&#x27;fixture-schema-checklist-smoke&#x27;]\"",
      "data-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:shared-readme-commands\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "Как `/plan` сверяет команды с shared README",
      "Local validation commands в shared README остаются источником правды",
      "Shared README command CI note",
      "data-testid=\"shared-readme-command-ci-note\"",
      "data-build-command=\"npm run build\"",
      "data-command=\"npm run smoke:shared-readme-commands\"",
      "data-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:shared-readme-commands\"",
      "data-parity-selector=\"[data-testid=&#x27;shared-readme-command-parity-smoke&#x27;]\"",
      "data-trigger-path=\"packages/shared/README.md\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как command parity smoke входит в Web build",
      "Web build запускает command parity smoke после shared fixture parity",
      "AI review schema API smoke marker",
      "data-testid=\"ai-review-schema-api-smoke-marker\"",
      "data-check-count=\"5\"",
      "data-api-route=\"/v1/ai/review-queue\"",
      "data-api-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#ai-review-queue-contract\"",
      "data-api-readme-anchor=\"AI Review Queue Contract\"",
      "data-api-readme-path=\"apps/api/README.md\"",
      "href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#ai-review-queue-contract\"",
      "data-schema-id=\"https://asts.local/schemas/ai-review-queue.schema.json\"",
      "data-schema-selector=\"[data-testid=&#x27;ai-review-schema-summary&#x27;]\"",
      "data-api-selector=\"[data-testid=&#x27;ai-review-receipt-api-link&#x27;]\"",
      "data-dom-parity-command=\"cd apps/web &amp;&amp; npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-parity-command=\"cd apps/web &amp;&amp; npm run smoke:ai-review-actions\"",
      "data-source-fixture=\"packages/shared/ai-review-queue.json\"",
      "data-protected-surface=\"/v1/ai/review-queue + /ai-review\"",
      "API review queue contract",
      "schema summary связан с backend contract",
      "сравнить `/plan` marker с `/ai-review` API README link",
      "AI review API README CI note",
      "data-testid=\"ai-review-api-readme-ci-note\"",
      "data-api-readme-path=\"apps/api/README.md\"",
      "data-api-route=\"/v1/ai/review-queue\"",
      "data-api-selector=\"[data-testid=&#x27;ai-review-receipt-api-link&#x27;]\"",
      "data-marker-selector=\"[data-testid=&#x27;ai-review-schema-api-smoke-marker&#x27;]\"",
      "data-dom-parity-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-trigger-path=\"apps/api/README.md\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как DOM parity smoke входит в Web build",
      "Web build запускает DOM parity smoke после route smoke",
      "API README live route gate note",
      "data-testid=\"api-readme-live-route-gate-note\"",
      "data-command=\"npm run smoke:api-readme-live-route\"",
      "data-live-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-marker-selector=\"[data-testid=&#x27;ai-review-api-readme-ci-note&#x27;]\"",
      "data-route-smoke-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-source-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как live DOM parity защищает API docs links",
      "затем проверяет `/plan` + `/ai-review` API README link на живом сервере",
      "API README live-route failure copy",
      "data-testid=\"api-readme-live-route-failure-copy\"",
      "data-command=\"npm run smoke:api-readme-live-route-failure-copy\"",
      "data-failing-command=\"npm run smoke:api-readme-live-route\"",
      "data-live-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-no-merge-copy=\"Не мержить, пока Web build снова держит API README live-route gate перед rendered routes parity checks\"",
      "data-owner-role=\"API owner + CI owner\"",
      "data-repair-targets=\".github/workflows/web-build.yml,/plan,apps/web/scripts/api-readme-live-route-gate.mjs,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;api-readme-live-route-gate-note&#x27;]\"",
      "Что делать, если API README live-route gate упал",
      "не мержить, пока API README live-route gate снова не зеленый",
      "AI review API README failure copy",
      "data-testid=\"ai-review-api-readme-failure-copy\"",
      "data-command=\"npm run smoke:ai-review-api-readme-failure-copy\"",
      "data-failing-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-live-gate-selector=\"[data-testid=&#x27;api-readme-live-route-gate-note&#x27;]\"",
      "data-marker-selector=\"[data-testid=&#x27;ai-review-api-readme-ci-note&#x27;]\"",
      "data-no-merge-copy=\"Не мержить, пока `/plan`, `/ai-review` и apps/api/README.md снова не указывают на один anchor\"",
      "data-owner-role=\"API owner + Product owner\"",
      "data-repair-targets=\"/plan,/ai-review,apps/api/README.md#ai-review-queue-contract\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Что делать, если API README parity падает",
      "сначала восстановить API README anchor, затем `/ai-review` link и `/plan` marker",
      "AI review API README rendered-route failure copy",
      "data-testid=\"ai-review-api-readme-rendered-route-failure-copy\"",
      "data-command=\"npm run smoke:ai-review-api-readme-rendered-route-failure-copy\"",
      "data-api-selector=\"[data-testid=&#x27;ai-review-receipt-api-link&#x27;]\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-live-gate-selector=\"[data-testid=&#x27;ai-review-api-readme-failure-copy&#x27;]\"",
      "data-marker-selector=\"[data-testid=&#x27;ai-review-api-readme-ci-note&#x27;]\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает `/plan` + `/ai-review` API README parity\"",
      "data-owner-role=\"API owner + QA owner\"",
      "data-repair-targets=\"/plan,/ai-review,apps/api/README.md#ai-review-queue-contract,apps/web/scripts/ai-review-api-readme-parity.mjs\"",
      "Что делать, если AI review API README parity упала в rendered routes",
      "не мержить, пока AI review API README parity снова не зеленый внутри rendered routes smoke",
      "AI review queue rendered-route failure copy",
      "data-testid=\"ai-review-queue-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/ai/review-queue\"",
      "data-command=\"npm run smoke:ai-review-queue-rendered-route-failure-copy\"",
      "data-expected-blocked-count=\"2\"",
      "data-expected-queue-count=\"3\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает AI review queue, owners и evidence на живом `/ai-review`\"",
      "data-owner-role=\"AI workflow owner + QA owner\"",
      "data-parity-command=\"npm run smoke:ai-review-actions\"",
      "data-repair-targets=\"/ai-review,packages/shared/ai-review-queue.json,apps/web/scripts/ai-review-action-parity.mjs,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;ai-review-confidence-queue&#x27;]\"",
      "Что делать, если AI review queue пропала в rendered routes",
      "не мержить, пока AI review queue снова не проходит rendered route coverage",
      "AI review receipt API rendered-route failure copy",
      "data-testid=\"ai-review-receipt-api-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/ai/review-queue\"",
      "data-api-service-path=\"apps/api/app/services/ai_review.py\"",
      "data-command=\"npm run smoke:ai-review-receipt-api-rendered-route-failure-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#ai-review-queue-contract\"",
      "data-expected-blocked-count=\"2\"",
      "data-expected-owner-count=\"3\"",
      "data-expected-queue-count=\"3\"",
      "data-expected-route-count=\"16\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает AI review API route, shared fixture и `/ai-review` receipt markers\"",
      "data-owner-role=\"API owner + AI workflow owner + QA owner\"",
      "data-parity-command=\"npm run smoke:ai-review-actions\"",
      "data-repair-targets=\"apps/api/app/main.py,apps/api/app/services/ai_review.py,packages/shared/ai-review-queue.json,/ai-review,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;ai-review-receipt-browser-loop&#x27;]\"",
      "Что делать, если AI review receipt API пропал в rendered routes",
      "не мержить, пока AI review receipt API снова не проходит rendered route coverage",
      "API README trigger smoke",
      "data-testid=\"api-readme-trigger-smoke\"",
      "data-command=\"npm run smoke:api-readme-trigger\"",
      "data-dom-parity-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-expected-workflow-path-count=\"2\"",
      "data-source-ci-note-selector=\"[data-testid=&#x27;ai-review-api-readme-ci-note&#x27;]\"",
      "data-trigger-path=\"apps/api/README.md\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как backend README запускает web parity",
      "apps/api/README.md должен быть в pull_request и push paths",
      "API README trigger failure copy",
      "data-testid=\"api-readme-trigger-failure-copy\"",
      "data-command=\"npm run smoke:api-readme-trigger-failure-copy\"",
      "data-expected-workflow-path-count=\"2\"",
      "data-failing-command=\"npm run smoke:api-readme-trigger\"",
      "data-no-merge-copy=\"Не мержить, пока apps/api/README.md снова не запускает Web build в pull_request и push paths\"",
      "data-owner-role=\"API owner + CI owner\"",
      "data-repair-targets=\"apps/api/README.md,.github/workflows/web-build.yml,/plan,[data-testid=&#x27;api-readme-trigger-smoke&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;api-readme-trigger-smoke&#x27;]\"",
      "Что делать, если backend README trigger упал",
      "не мержить, пока trigger smoke и live API README parity снова не зеленые",
      "API README trigger rendered-route failure copy",
      "data-testid=\"api-readme-trigger-rendered-route-failure-copy\"",
      "data-command=\"npm run smoke:api-readme-trigger-rendered-route-failure-copy\"",
      "data-dom-parity-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-expected-route-count=\"16\"",
      "data-expected-workflow-path-count=\"2\"",
      "data-failing-command=\"npm run smoke:ai-review-api-readme -- --url http://127.0.0.1:4177\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает API README trigger path и live parity chain\"",
      "data-owner-role=\"API owner + QA owner\"",
      "data-repair-targets=\".github/workflows/web-build.yml,/plan,apps/api/README.md,apps/web/scripts/api-readme-trigger-smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;api-readme-trigger-failure-copy&#x27;]\"",
      "Что делать, если API README trigger chain пропала в rendered routes",
      "не мержить, пока API README trigger chain снова не зеленая внутри rendered routes smoke",
      "Schema docs link parity smoke",
      "data-testid=\"schema-docs-link-parity-smoke\"",
      "data-anchor=\"packages/shared/README.md#shared-schema-index\"",
      "data-anchor-slug=\"shared-schema-index\"",
      "data-readme-heading=\"Shared Schema Index\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-link-selector=\"[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-checklist-selector=\"[data-testid=&#x27;fixture-schema-checklist-smoke&#x27;]\"",
      "data-schema-count=\"3\"",
      "data-checklist-schema-count=\"5\"",
      "Shared schema README",
      "route smoke проверяет оба selector и один anchor",
      "Schema docs README existence smoke",
      "data-testid=\"schema-docs-readme-existence-smoke\"",
      "data-expected-rows=\"5\"",
      "data-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:schema-docs-readme\"",
      "Как `/plan` проверяет существование shared schema index",
      "README держит `## Shared Schema Index` для GitHub anchor",
      "Schema docs README CI note",
      "data-testid=\"schema-docs-readme-ci-note\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/packages/shared/README.md#shared-schema-index\"",
      "data-expected-rows=\"5\"",
      "data-link-selector=\"[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-readme-heading=\"Shared Schema Index\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-smoke-command=\"npm run smoke:schema-docs-readme\"",
      "data-source-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:schema-docs-readme\"",
      "data-trigger-path=\"packages/shared/README.md\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как README existence smoke входит в Web build",
      "Web build запускает README existence smoke до route smoke",
      "Schema docs README workflow smoke",
      "data-testid=\"schema-docs-readme-workflow-smoke\"",
      "data-command=\"npm run smoke:schema-docs-workflow\"",
      "data-expected-workflow-path-count=\"2\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-source-ci-note-selector=\"[data-testid=&#x27;schema-docs-readme-ci-note&#x27;]\"",
      "data-source-smoke-command=\"npm run smoke:schema-docs-readme\"",
      "data-trigger-path=\"packages/shared/README.md\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как schema docs note сверяется с Web build",
      "packages/shared/README.md должен быть в pull_request и push paths",
      "Schema docs workflow failure copy",
      "data-testid=\"schema-docs-workflow-failure-copy\"",
      "data-command=\"npm run smoke:schema-docs-workflow-failure-copy\"",
      "data-expected-workflow-path-count=\"2\"",
      "data-failing-command=\"npm run smoke:schema-docs-workflow\"",
      "data-no-merge-copy=\"Не мержить, пока packages/shared/README.md снова не запускает Web build и schema docs workflow smoke\"",
      "data-owner-role=\"Schema owner + CI owner\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-repair-targets=\"packages/shared/README.md,.github/workflows/web-build.yml,/plan,[data-testid=&#x27;schema-docs-readme-workflow-smoke&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;schema-docs-readme-workflow-smoke&#x27;]\"",
      "Что делать, если schema docs workflow упал",
      "не мержить, пока schema docs workflow smoke и README existence smoke снова не зеленые",
      "Schema docs README live route gate note",
      "data-testid=\"schema-docs-readme-live-route-gate-note\"",
      "data-command=\"npm run smoke:schema-docs-live-route\"",
      "data-link-selector=\"[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-marker-selector=\"[data-testid=&#x27;schema-docs-readme-ci-note&#x27;]\"",
      "data-readme-command=\"npm run smoke:schema-docs-readme\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-route-smoke-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-source-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:schema-docs-readme\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как live route smoke защищает schema docs links",
      "затем route smoke проверяет `/plan` schema docs link на живом сервере",
      "Schema docs live-route failure copy",
      "data-testid=\"schema-docs-live-route-failure-copy\"",
      "data-command=\"npm run smoke:schema-docs-live-route-failure-copy\"",
      "data-failing-command=\"npm run smoke:schema-docs-live-route\"",
      "data-no-merge-copy=\"Не мержить, пока Web build снова держит schema docs live-route gate перед rendered routes smoke\"",
      "data-owner-role=\"Schema owner + CI owner\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-repair-targets=\".github/workflows/web-build.yml,/plan,packages/shared/README.md,[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;schema-docs-readme-live-route-gate-note&#x27;]\"",
      "Что делать, если schema docs live-route gate упал",
      "не мержить, пока schema docs live-route gate снова не зеленый",
      "Schema docs README failure copy",
      "data-testid=\"schema-docs-readme-failure-copy\"",
      "data-command=\"npm run smoke:schema-docs-readme-failure-copy\"",
      "data-failing-command=\"npm run smoke:schema-docs-live-route\"",
      "data-no-merge-copy=\"Не мержить, пока `/plan` и packages/shared/README.md#shared-schema-index снова не показывают один schema index\"",
      "data-owner-role=\"Schema owner + Product owner\"",
      "data-repair-targets=\"/plan,packages/shared/README.md#shared-schema-index,[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;schema-docs-readme-live-route-gate-note&#x27;]\"",
      "Что делать, если schema docs parity упал",
      "не мержить, пока schema docs smoke и route smoke снова не зеленые",
      "Schema docs rendered-route failure copy",
      "data-testid=\"schema-docs-rendered-route-failure-copy\"",
      "data-command=\"npm run smoke:schema-docs-rendered-route-failure-copy\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-link-selector=\"[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает schema docs link и shared README parity на живом `/plan`\"",
      "data-owner-role=\"Schema owner + QA owner\"",
      "data-readme-path=\"packages/shared/README.md\"",
      "data-repair-targets=\"/plan,packages/shared/README.md#shared-schema-index,apps/web/scripts/smoke.mjs,[data-testid=&#x27;schema-docs-link&#x27;]\"",
      "data-source-marker-selector=\"[data-testid=&#x27;schema-docs-readme-failure-copy&#x27;]\"",
      "Что делать, если schema docs пропали в rendered routes",
      "не мержить, пока schema docs markers снова не проходят rendered routes smoke",
      "Source owner receipts rendered-route failure copy",
      "data-testid=\"source-owner-receipts-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/sources/owner-receipts\"",
      "data-command=\"npm run smoke:source-owner-receipts-rendered-route-failure-copy\"",
      "data-docs-command=\"npm run smoke:source-receipt-docs-link -- --url http://127.0.0.1:4177\"",
      "data-expected-history-count=\"4\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke:source-receipt-docs-link -- --url http://127.0.0.1:4177\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает `/sources` owner receipt history и API docs link\"",
      "data-owner-role=\"Sources owner + QA owner\"",
      "data-parity-command=\"npm run smoke:owner-receipts\"",
      "data-repair-targets=\"/sources,packages/shared/source-owner-receipts.json,apps/web/scripts/source-receipt-docs-link-browser.mjs,apps/api/README.md#source-owner-receipt-contract\"",
      "data-source-marker-selector=\"[data-testid=&#x27;schema-docs-rendered-route-failure-copy&#x27;]\"",
      "Что делать, если source owner receipts пропали в rendered routes",
      "не мержить, пока source owner receipts снова не проходят rendered route coverage",
      "Owner receipt API rendered-route failure copy",
      "data-testid=\"owner-receipt-api-rendered-route-failure-copy\"",
      "data-api-service-path=\"apps/api/app/services/source_owner_receipts.py\"",
      "data-command=\"npm run smoke:owner-receipt-api-rendered-route-failure-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-owner-receipt-contract\"",
      "data-expected-blocked-until-restored-count=\"2\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает owner receipt API route, shared fixture и `/sources` history markers\"",
      "data-owner-role=\"API owner + Sources owner + QA owner\"",
      "data-repair-targets=\"apps/api/app/main.py,apps/api/app/services/source_owner_receipts.py,packages/shared/source-owner-receipts.json,/sources,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;source-owner-receipt-history&#x27;]\"",
      "Что делать, если owner receipt API пропал в rendered routes",
      "не мержить, пока owner receipt API снова не проходит rendered route coverage",
      "Source freshness rendered-route failure copy",
      "data-testid=\"source-freshness-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/sources/freshness\"",
      "data-breach-types=\"stale,missing,parse_failed,hash_mismatch\"",
      "data-command=\"npm run smoke:source-freshness-rendered-route-failure-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-freshness-contract\"",
      "data-expected-blocked-count=\"4\"",
      "data-expected-breach-count=\"4\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает source freshness queue, breach types и AI gate на живом `/sources`\"",
      "data-owner-role=\"Sources owner + QA owner\"",
      "data-repair-targets=\"/sources,apps/web/lib/mock-data.ts,apps/web/scripts/smoke.mjs,apps/api/README.md#source-freshness-contract\"",
      "data-source-marker-selector=\"[data-testid=&#x27;source-freshness-breach-queue&#x27;]\"",
      "Что делать, если source freshness пропала в rendered routes",
      "не мержить, пока source freshness снова не проходит rendered route coverage",
      "Source freshness docs rendered-route failure copy",
      "data-testid=\"source-freshness-docs-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/sources/freshness\"",
      "data-command=\"npm run smoke:source-freshness-docs-rendered-route-failure-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-freshness-contract\"",
      "data-expected-breach-count=\"4\"",
      "data-expected-route-count=\"16\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает source freshness docs link и API README anchor на живом `/sources`\"",
      "data-owner-role=\"Sources owner + Docs owner + QA owner\"",
      "data-repair-targets=\"/sources,apps/api/README.md#source-freshness-contract,apps/web/lib/mock-data.ts,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;source-freshness-docs-link&#x27;]\"",
      "Что делать, если source freshness docs пропали в rendered routes",
      "не мержить, пока source freshness docs link снова не проходит rendered route coverage",
      "Owner receipt docs rendered-route failure copy",
      "data-testid=\"owner-receipt-docs-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/sources/owner-receipts\"",
      "data-command=\"npm run smoke:owner-receipt-docs-rendered-route-failure-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-owner-receipt-contract\"",
      "data-expected-history-count=\"4\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke:source-receipt-docs-link -- --url http://127.0.0.1:4177\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает owner receipt docs link и browser loop на живом `/sources`\"",
      "data-owner-role=\"Sources owner + Docs owner + QA owner\"",
      "data-parity-command=\"npm run smoke:owner-receipts\"",
      "data-repair-targets=\"/sources,apps/api/README.md#source-owner-receipt-contract,apps/web/scripts/source-receipt-docs-link-browser.mjs,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;source-owner-receipt-history-browser-loop&#x27;]\"",
      "Что делать, если owner receipt docs пропали в rendered routes",
      "не мержить, пока owner receipt docs снова не проходят rendered route coverage",
      "FNS approvals rendered-route failure copy",
      "data-testid=\"fns-approvals-rendered-route-failure-copy\"",
      "data-api-route=\"/v1/sources/connectors\"",
      "data-command=\"npm run smoke:fns-approvals-rendered-route-failure-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#fns-smoke-contract\"",
      "data-expected-approval-count=\"5\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает FNS Legal approvals на живом `/sources`\"",
      "data-owner-role=\"Legal owner + QA owner\"",
      "data-parity-command=\"npm run smoke:fns-approvals\"",
      "data-repair-targets=\"/sources,packages/shared/fns-connector-gate.json,apps/web/scripts/fns-approvals-parity.mjs,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;fns-real-network-smoke-gate&#x27;]\"",
      "Что делать, если FNS approvals пропали в rendered routes",
      "не мержить, пока FNS approvals снова не проходят rendered route coverage",
      "FNS approvals docs rendered-route failure copy",
      "data-testid=\"fns-approvals-docs-rendered-route-failure-copy\"",
      "data-command=\"npm run smoke:fns-approvals-docs-rendered-route-failure-copy\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова подтверждает FNS docs link, Legal approvals и API README anchor на живом `/sources`\"",
      "data-owner-role=\"Legal owner + Docs owner + QA owner\"",
      "data-repair-targets=\"/sources,apps/api/README.md#fns-smoke-contract,packages/shared/fns-connector-gate.json,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;fns-network-gate-docs-link&#x27;]\"",
      "Что делать, если FNS approvals docs пропали в rendered routes",
      "не мержить, пока FNS docs link снова не проходит rendered route coverage",
      "FNS real-network approval API copy",
      "data-testid=\"fns-real-network-approval-api-copy\"",
      "data-command=\"npm run smoke:fns-real-network-approval-api-copy\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#fns-real-network-approval-api-copy\"",
      "data-expected-approval-count=\"5\"",
      "data-expected-route-count=\"16\"",
      "data-fixture-path=\"packages/shared/fns-connector-gate.json\"",
      "data-no-merge-copy=\"Не мержить real-network FNS smoke, пока approval_api_copy подтверждает Legal owner, protected secrets, safe INN/OGRN и checksum freshness receipt.\"",
      "data-owner-role=\"Legal owner + API owner + QA owner\"",
      "data-repair-targets=\"packages/shared/fns-connector-gate.json,apps/api/app/services/connectors.py,apps/api/README.md,/sources,apps/web/scripts/fns-real-network-approval-api-copy.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;fns-real-network-approval-api-copy&#x27;]\"",
      "Что должен сказать API перед включением сетевого smoke",
      "не мержить, пока approval API copy не проходит backend, shared и web smoke",
      "Web build workflow file smoke",
      "data-testid=\"web-build-workflow-file-smoke\"",
      "data-command=\"npm run smoke:web-build-workflow\"",
      "data-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:web-build-workflow\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "data-working-directory=\"apps/web\"",
      "data-node-version=\"22\"",
      "data-expected-command-count=\"43\"",
      "data-expected-path-count=\"7\"",
      "data-ci-note-selectors=\"[data-testid=&#x27;shared-readme-command-ci-note&#x27;],[data-testid=&#x27;ai-review-api-readme-ci-note&#x27;],[data-testid=&#x27;ai-review-queue-rendered-route-failure-copy&#x27;],[data-testid=&#x27;ai-review-receipt-api-rendered-route-failure-copy&#x27;],[data-testid=&#x27;api-readme-live-route-gate-note&#x27;],[data-testid=&#x27;api-readme-live-route-failure-copy&#x27;],[data-testid=&#x27;ai-review-api-readme-failure-copy&#x27;],[data-testid=&#x27;ai-review-api-readme-rendered-route-failure-copy&#x27;],[data-testid=&#x27;api-readme-trigger-smoke&#x27;],[data-testid=&#x27;api-readme-trigger-failure-copy&#x27;],[data-testid=&#x27;api-readme-trigger-rendered-route-failure-copy&#x27;],[data-testid=&#x27;schema-docs-readme-ci-note&#x27;],[data-testid=&#x27;schema-docs-readme-workflow-smoke&#x27;],[data-testid=&#x27;schema-docs-workflow-failure-copy&#x27;],[data-testid=&#x27;schema-docs-readme-live-route-gate-note&#x27;],[data-testid=&#x27;schema-docs-live-route-failure-copy&#x27;],[data-testid=&#x27;schema-docs-readme-failure-copy&#x27;],[data-testid=&#x27;schema-docs-rendered-route-failure-copy&#x27;],[data-testid=&#x27;source-owner-receipts-rendered-route-failure-copy&#x27;],[data-testid=&#x27;owner-receipt-api-rendered-route-failure-copy&#x27;],[data-testid=&#x27;source-freshness-rendered-route-failure-copy&#x27;],[data-testid=&#x27;source-freshness-docs-rendered-route-failure-copy&#x27;],[data-testid=&#x27;fns-approvals-rendered-route-failure-copy&#x27;],[data-testid=&#x27;fns-approvals-docs-rendered-route-failure-copy&#x27;],[data-testid=&#x27;fns-real-network-approval-api-copy&#x27;],[data-testid=&#x27;owner-receipt-docs-rendered-route-failure-copy&#x27;],[data-testid=&#x27;shared-validation-workflow-ci-note&#x27;],[data-testid=&#x27;shared-validation-workflow-step-smoke&#x27;],[data-testid=&#x27;shared-validation-workflow-failure-copy&#x27;],[data-testid=&#x27;shared-validation-live-route-gate-note&#x27;],[data-testid=&#x27;shared-validation-failure-copy&#x27;],[data-testid=&#x27;shared-validation-rendered-route-failure-copy&#x27;],[data-testid=&#x27;web-build-workflow-self-check-note&#x27;],[data-testid=&#x27;web-build-live-route-gate-note&#x27;],[data-testid=&#x27;web-build-failure-copy&#x27;],[data-testid=&#x27;web-build-rendered-route-failure-copy&#x27;]\"",
      "Как `/plan` сверяет реальный Web build workflow",
      "сверяет 43 build/smoke commands",
      "Web build workflow self-check note",
      "data-testid=\"web-build-workflow-self-check-note\"",
      "data-command=\"npm run smoke:web-build-self-check\"",
      "data-file-smoke-command=\"npm run smoke:web-build-workflow\"",
      "data-file-smoke-selector=\"[data-testid=&#x27;web-build-workflow-file-smoke&#x27;]\"",
      "data-source-smoke-command=\"cd apps/web &amp;&amp; npm run smoke:web-build-workflow\"",
      "data-trigger-path=\".github/workflows/web-build.yml\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как Web build проверяет собственный workflow",
      ".github/workflows/web-build.yml запускает Web build при изменении workflow",
      "Web build live route gate note",
      "data-testid=\"web-build-live-route-gate-note\"",
      "data-command=\"npm run smoke:web-build-live-route\"",
      "data-file-smoke-selector=\"[data-testid=&#x27;web-build-workflow-file-smoke&#x27;]\"",
      "data-marker-selector=\"[data-testid=&#x27;web-build-workflow-self-check-note&#x27;]\"",
      "data-route-smoke-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-source-smoke-command=\"npm run smoke:web-build-self-check\"",
      "data-trigger-path=\".github/workflows/web-build.yml\"",
      "data-workflow-name=\"Web build\"",
      "data-workflow-path=\".github/workflows/web-build.yml\"",
      "data-workflow-href=\"https://github.com/info14fourteen-creator/ASTS/actions/workflows/web-build.yml\"",
      "Как live route smoke защищает Web build",
      "затем route smoke проверяет `/plan` web build markers на живом сервере",
      "Web build failure copy",
      "data-testid=\"web-build-failure-copy\"",
      "data-command=\"npm run smoke:web-build-failure-copy\"",
      "data-failing-command=\"npm run smoke:web-build-live-route\"",
      "data-no-merge-copy=\"Не мержить, пока Web build, `/plan` и .github/workflows/web-build.yml снова не показывают один workflow gate\"",
      "data-owner-role=\"Frontend owner + CI owner\"",
      "data-repair-targets=\"/plan,.github/workflows/web-build.yml,apps/web/scripts/web-build-workflow-file.mjs,apps/web/scripts/smoke.mjs\"",
      "data-source-marker-selector=\"[data-testid=&#x27;web-build-live-route-gate-note&#x27;]\"",
      "Что делать, если Web build gate упал",
      "не мержить, пока Web build smoke и route smoke снова не зеленые",
      "Web build rendered-route failure copy",
      "data-testid=\"web-build-rendered-route-failure-copy\"",
      "data-command=\"npm run smoke:web-build-rendered-route-failure-copy\"",
      "data-expected-route-count=\"16\"",
      "data-failing-command=\"npm run smoke -- --url http://127.0.0.1:4177/\"",
      "data-no-merge-copy=\"Не мержить, пока rendered routes smoke снова проходит 16 маршрутов app.site.ru на живом сервере\"",
      "data-owner-role=\"Frontend owner + QA owner\"",
      "data-repair-targets=\"apps/web/scripts/smoke.mjs,apps/web/app/plan/page.tsx,.github/workflows/web-build.yml,/plan\"",
      "data-source-marker-selector=\"[data-testid=&#x27;web-build-failure-copy&#x27;]\"",
      "Что делать, если rendered routes упали",
      "не мержить, пока rendered routes smoke снова не зеленый на PR",
      "asts-app-site-ru-12",
      "19 static routes",
      "Partner quickstart",
      "data-testid=\"partner-quickstart\"",
      "data-branch-prefix=\"codex/\"",
      "data-step-count=\"4\"",
      "git clone git@github.com:info14fourteen-creator/ASTS.git",
      "git checkout -b codex/&lt;short-task-name&gt;",
      "Prompt for partner Codex",
      "не пушь напрямую в main",
      "Fixture coverage",
      "Pre-win rows",
      "Execution rows",
      "Execution artifacts",
      "Outcome states",
      "Fixture drift guard",
      "data-testid=\"fixture-drift-warning\"",
      "data-status=\"aligned\"",
      "Нет дрейфа между smoke и fixture",
      "Fixture drift quarantine copy",
      "data-testid=\"fixture-drift-quarantine-copy\"",
      "data-status=\"standby\"",
      "data-action-count=\"4\"",
      "Quarantine готов, но не включен",
      "AI может читать demo fixture",
      "Merge разрешен только пока Web build",
      "fixture-drift-warning / route smoke / packages/shared/demo-data/asts-demo.json",
      "Freeze",
      "Release",
      `data-aligned-count="${fixtureDriftCheckCount}"`,
      `data-total-count="${fixtureDriftCheckCount}"`,
      `data-expected="${preWinTenders.length}"`,
      `data-actual="${preWinTenders.length}"`,
      `data-expected="${executionTenders.length}"`,
      `data-actual="${executionTenders.length}"`,
      `data-expected="${executionDocuments.length}"`,
      `data-actual="${executionDocuments.length}"`,
      `data-expected="${preWinOutcomeCounts}"`,
      `data-actual="${preWinOutcomeCounts}"`,
      `${preWinTenders.length}`,
      `${executionTenders.length}`,
      `${demoData.documents.length}`,
      `${executionDocuments.length}`,
      `${demoData.tasks.length}`,
      "3/1/1",
    ],
  },
  {
    path: "/tenders",
    status: 200,
    mustInclude: [
      "Процедуры",
      "Outcome filters",
      "Owner approval receipt",
      "data-testid=\"owner-approval-browser-loop\"",
      "Owner approval receipt history",
      "data-testid=\"owner-approval-receipt-history\"",
      "Owner approval handoff lock",
      "data-testid=\"owner-approval-handoff-lock\"",
      "data-approved-count=\"1\"",
      "data-approved-with-receipt=\"1\"",
      "data-approved-without-receipt=\"0\"",
      "data-execution-ready-count=\"1\"",
      "Approved outcome не попадает в execution без receipt",
      "execution handoff allowed",
      "execution handoff locked",
      `data-history-count="${preWinTenders.length}"`,
      `data-last-approved="${approvedPreWinTender.tender_id}"`,
      "Последние подтверждения перед handoff",
      "ready for execution handoff",
      "blocked before handoff",
      "data-active-outcome=\"all\"",
      "data-visible-count=\"4\"",
      "ожидают owner review",
      "нет owner approval",
      "0373100042626000001",
      approvedPreWinTender.outcome.source_ref,
    ],
  },
  ...outcomeFilterRouteChecks,
  ...tenderDetailRouteChecks,
  {
    path: "/tenders/unknown-id",
    status: 404,
    mustInclude: [
      "Карточка процедуры не найдена",
      "unknown tender id",
      "pre-win id из shared fixture",
      "Source-id mismatch hint",
      "raw-eis-*",
      "regNumber",
      "/execution",
    ],
  },
  {
    path: "/tasks",
    status: 200,
    mustInclude: [
      "Задачи и эскалации",
      "Automation pause policy",
      "Когда 12-минутный цикл должен остановиться",
      "каждая правка должна собрать 19 static routes",
    ],
  },
  {
    path: "/ai-review",
    status: 200,
    mustInclude: [
      "AI разбор процедур",
      "AI review schema summary",
      "data-testid=\"ai-review-schema-summary\"",
      "data-schema-id=\"https://asts.local/schemas/ai-review-queue.schema.json\"",
      "data-check-count=\"14\"",
      "data-threshold=\"0.85\"",
      "data-blocked-below=\"0.75\"",
      "data-fact-types=\"requirement,supplier_quote,economics\"",
      "data-owner-roles=\"tender_manager,supplier_manager,finance_owner\"",
      "data-source-host=\"zakupki.gov.ru\"",
      "data-protected-surface=\"/v1/ai/review-queue + /ai-review\"",
      "Low-confidence owner review",
      "data-testid=\"ai-review-confidence-queue\"",
      "data-total-count=\"3\"",
      "data-review-required-count=\"1\"",
      "data-blocked-count=\"2\"",
      "data-source-evidence-count=\"3\"",
      "data-threshold=\"0.85\"",
      "data-fact-type=\"requirement\"",
      "data-fact-type=\"supplier_quote\"",
      "data-fact-type=\"economics\"",
      "data-required-action=\"confirm requirement interpretation before supplier request\"",
      "data-required-action=\"request supplier clarification and keep economics blocked\"",
      "data-required-action=\"finance owner must approve or keep outcome locked\"",
      "data-status=\"review_required\"",
      "data-status=\"blocked\"",
      "raw-eis-0373100042626000001",
      "raw-eis-32211984571",
      "raw-eis-0173200001426000044",
      "AI review owner receipt",
      "data-testid=\"ai-review-owner-receipt-rules\"",
      "data-rule-count=\"3\"",
      "data-allowed-decisions=\"confirmed,corrected,blocked\"",
      "data-required-fields=\"evidence_ref,confidence_at_review,source_checksum_sha256\"",
      "data-owner=\"tender_manager\"",
      "data-owner=\"supplier_manager\"",
      "data-owner=\"finance_owner\"",
      "supplier_clarification_ref",
      "receipt required",
      "AI review receipt browser loop",
      "data-testid=\"ai-review-receipt-browser-loop\"",
      "data-testid=\"ai-review-receipt-api-link\"",
      "data-api-route=\"/v1/ai/review-queue\"",
      "data-api-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#ai-review-queue-contract\"",
      "href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#ai-review-queue-contract\"",
      "API / AI review queue",
      "confirm requirement interpretation before supplier request",
      "request supplier clarification and keep economics blocked",
      "finance owner must approve or keep outcome locked",
      "data-selector=\"[data-testid=&#x27;ai-review-owner-receipt-rules&#x27;] [data-owner]\"",
      "data-owner-count=\"3\"",
      "data-owners=\"tender_manager,supplier_manager,finance_owner\"",
      "Assert decisions",
      "AI review browser loop",
      "data-testid=\"ai-review-confidence-browser-loop\"",
      "data-selector=\"[data-testid=&#x27;ai-review-confidence-queue&#x27;] [data-status=&#x27;blocked&#x27;]\"",
      "Assert confidence",
      "Assert owner",
      "Assert evidence",
      "owner review required",
    ],
  },
  {
    path: "/execution",
    status: 200,
    mustInclude: [
      "Исполнение после победы",
      "Execution fixture inbox",
      "Execution handoff artifacts",
      "Execution artifact empty guard",
      "data-testid=\"execution-artifact-empty-guard\"",
      "Execution artifact blocked fixture",
      "data-testid=\"execution-artifact-blocked-fixture\"",
      "Execution blocked browser loop",
      "data-testid=\"execution-blocked-browser-loop\"",
      "data-testid=\"execution-browser-ci-note\"",
      "data-fallback=\"route-smoke-html-contract\"",
      "data-selector=\"",
      "execution-artifact-blocked-fixture",
      "CI fallback",
      "Если in-app browser bridge недоступен, route smoke проверяет HTML contract.",
      "Без этих маркеров PR не считается проверенным.",
      `data-contract-count="${executionTenders.length}"`,
      `data-artifact-count="${executionDocuments.length}"`,
      "data-min-artifacts=\"3\"",
      "data-status=\"ready\"",
      "data-status=\"blocked\"",
      "data-artifact-count=\"0\"",
      "data-missing-artifacts=\"3\"",
      "Assert status",
      "Assert evidence",
      "Победа не запускает исполнение без raw artifacts",
      "execution handoff blocked",
      "handoff ready",
      "handoff blocked",
      "Победа не запускает исполнение без raw artifacts",
      "exec-2026-0007",
      "execution_owner",
      "raw-etp-procedure-room-0373100042626000001",
      "raw-eis-0373100099926000012",
      ...executionDocumentMarkers,
    ],
  },
  {
    path: "/sources",
    status: 200,
    mustInclude: [
      "Источники данных",
      "ЕИС / zakupki.gov.ru",
      "Source URL health state",
      "data-testid=\"source-url-health-state\"",
      "data-ready-count=\"1\"",
      "data-quarantine-count=\"1\"",
      "data-unavailable-count=\"1\"",
      "Source quarantine browser loop",
      "data-testid=\"source-quarantine-browser-loop\"",
      "data-status=\"quarantine\"",
      "data-ai-gate=\"blocked\"",
      "FNS source readiness",
      "data-testid=\"fns-source-readiness-card\"",
      "data-connector-id=\"fns-egrul-nalog-ru\"",
      "data-status=\"contract-only\"",
      "data-ai-gate=\"manual_review_until_secrets\"",
      "data-required-secrets=\"FNS_API_BASE_URL,FNS_API_TOKEN\"",
      "raw/fns/{inn}/{artifact_id}",
      "data-capability=\"fetch_by_inn\"",
      "data-capability=\"fetch_by_ogrn\"",
      "data-capability=\"fetch_extract\"",
      "data-capability=\"normalize\"",
      "FNS real-network smoke gate",
      "data-testid=\"fns-real-network-smoke-gate\"",
      "data-network-smoke-status=\"contract_only\"",
      "data-owner=\"Legal\"",
      "data-safe-test-pair-required=\"true\"",
      "data-approval-count=\"5\"",
      "data-approval-api-route=\"/v1/sources/connectors\"",
      "data-approval-api-status=\"contract_only\"",
      "data-approval-api-owner=\"Legal\"",
      "data-approval-api-request-copy=\"Request Legal approval before enabling real FNS network smoke.\"",
      "data-approval-api-blocked-copy=\"Do not enable FNS real-network smoke until all five approvals are recorded.\"",
      "data-approval-api-next-action=\"Create protected environment secrets and record safe test INN/OGRN pair after Legal approval.\"",
      "data-approval-api-no-merge-copy=\"Не мержить real-network FNS smoke, пока approval_api_copy подтверждает Legal owner, protected secrets, safe INN/OGRN и checksum freshness receipt.\"",
      "data-testid=\"fns-real-network-approval-api-copy\"",
      "Request Legal approval before enabling real FNS network smoke.",
      "Do not enable FNS real-network smoke until all five approvals are recorded.",
      "CI must not call FNS until the real-network gate is explicitly approved.",
      "safe test INN and OGRN pair is recorded",
      "FNS network gate browser loop",
      "data-testid=\"fns-network-gate-browser-loop\"",
      "data-testid=\"fns-network-gate-docs-link\"",
      "data-api-route=\"/v1/sources/connectors\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#fns-smoke-contract\"",
      "href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#fns-smoke-contract\"",
      "API README / Legal gate",
      "data-selector=\"[data-testid=&#x27;fns-real-network-smoke-gate&#x27;] [data-approval]\"",
      "Assert approvals",
      "Assert Legal",
      "FNS connector browser loop",
      "data-testid=\"fns-connector-browser-loop\"",
      "data-selector=\"[data-testid=&#x27;fns-source-readiness-card&#x27;]\"",
      "data-secret-count=\"2\"",
      "data-capability-count=\"4\"",
      "Freshness breach queue",
      "data-testid=\"source-freshness-breach-queue\"",
      "data-total-count=\"4\"",
      "data-ai-blocked-count=\"4\"",
      "data-breach-types=\"stale,missing,parse_failed,hash_mismatch\"",
      "data-breach-type=\"stale\"",
      "data-breach-type=\"missing\"",
      "data-breach-type=\"parse_failed\"",
      "data-breach-type=\"hash_mismatch\"",
      "data-raw-artifact-id=\"raw-eis-32211984571\"",
      "Freshness breach browser loop",
      "data-testid=\"source-freshness-browser-loop\"",
      "data-api-route=\"/v1/sources/freshness\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-freshness-contract\"",
      "data-expected-count=\"4\"",
      "data-selector=\"[data-testid=&#x27;source-freshness-breach-queue&#x27;] [data-ai-gate=&#x27;blocked&#x27;]\"",
      "data-testid=\"source-freshness-docs-link\"",
      "API README / freshness",
      "Freshness owner receipt",
      "data-testid=\"source-freshness-owner-receipt-rules\"",
      "data-ai-gate=\"blocked_until_owner_receipt\"",
      "data-receipt-status=\"restored\"",
      "data-rule-count=\"4\"",
      "data-required-receipt-status=\"restored\"",
      "owner receipt required",
      "Source owner receipt history",
      "data-testid=\"source-owner-receipt-history\"",
      "data-api-route=\"/v1/sources/owner-receipts\"",
      "data-history-count=\"4\"",
      "data-resolution-statuses=\"restored,accepted_with_note,restored,still_blocked\"",
      "data-resolution-status=\"accepted_with_note\"",
      "data-resolution-status=\"still_blocked\"",
      "data-ai-gate=\"ready_after_receipt\"",
      "data-ai-gate=\"blocked_until_restored\"",
      "raw-eis-32211984571-v2",
      "official-absence-eis-0373100099926000012",
      "normalized-eis-0173200001426000044-v3",
      "raw-etp-procedure-room-0373100042626000001-refetch",
      "Source owner receipt history browser loop",
      "data-testid=\"source-owner-receipt-history-browser-loop\"",
      "data-selector=\"[data-testid=&#x27;source-owner-receipt-history&#x27;] [data-resolution-status]\"",
      "data-api-route=\"/v1/sources/owner-receipts\"",
      "data-docs-href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-owner-receipt-contract\"",
      "data-testid=\"source-owner-receipt-docs-link\"",
      "href=\"https://github.com/info14fourteen-creator/ASTS/blob/codex/app-site-shell/apps/api/README.md#source-owner-receipt-contract\"",
      "API README / owner receipts",
      "data-ai-gates=\"ready_after_receipt,blocked_until_restored\"",
      "data-resolution-statuses=\"restored,accepted_with_note,still_blocked\"",
      "data-blocked-count=\"2\"",
      "Assert history",
      "Assert gates",
      "Source receipt browser loop",
      "data-testid=\"source-receipt-browser-loop\"",
      "data-receipt-status=\"restored\"",
      "data-required-fields=\"new_raw_artifact_id,new_checksum_sha256,audit_note\"",
      "data-selector=\"[data-testid=&#x27;source-freshness-owner-receipt-rules&#x27;] [data-required-receipt-status=&#x27;restored&#x27;]\"",
      "Assert restored",
      "Assert fields",
      "refresh primary-source payload before AI scoring",
      "fetch and store the missing procurement document raw artifact",
      "send the payload to manual schema review and keep AI blocked",
      "quarantine artifact and refetch from official ETP API",
      "data-selector=\"",
      "source-url-health-state",
      "[data-status=&#x27;quarantine&#x27;]",
      "Assert raw",
      "Assert AI gate",
      "quarantine blocks AI",
      "raw-eis-0373100099926000012",
      "raw-eis-0173200001426000044",
      "raw-etp-procedure-room-0373100042626000001",
      lockedPreWinTender.source.raw_artifact_id,
      lockedPreWinTender.outcome.owner_role,
      "connector timeout",
      "manual review before AI",
      "schema drift",
      "Source intake contract",
      "AI blocked until complete",
    ],
  },
  {
    path: "/no-such-route",
    status: 404,
    mustInclude: ["Маршрут не найден", "сверить текущий 80-пунктовый план разработки"],
  },
];

const staleMarkers = ["16 static routes", "18 static routes"];

function parseBaseUrl() {
  const urlFlag = process.argv.find((arg) => arg.startsWith("--url="));

  if (urlFlag) {
    return urlFlag.slice("--url=".length).replace(/\/$/, "");
  }

  const urlIndex = process.argv.indexOf("--url");
  if (urlIndex !== -1 && process.argv[urlIndex + 1]) {
    return process.argv[urlIndex + 1].replace(/\/$/, "");
  }

  return (process.env.ASTS_WEB_BASE_URL || defaultBaseUrl).replace(/\/$/, "");
}

async function checkRoute(baseUrl, check) {
  const response = await fetch(`${baseUrl}${check.path}`);
  const html = await response.text();
  const failures = [];

  if (response.status !== check.status) {
    failures.push(`expected HTTP ${check.status}, got ${response.status}`);
  }

  for (const marker of check.mustInclude) {
    if (!html.includes(marker)) {
      failures.push(`missing marker: ${marker}`);
    }
  }

  for (const staleMarker of staleMarkers) {
    if (html.includes(staleMarker)) {
      failures.push(`stale marker present: ${staleMarker}`);
    }
  }

  return {
    failures,
    path: check.path,
    status: response.status,
  };
}

const baseUrl = parseBaseUrl();
const results = [];

for (const check of routeChecks) {
  results.push(await checkRoute(baseUrl, check));
}

const failed = results.filter((result) => result.failures.length > 0);

for (const result of results) {
  const state = result.failures.length > 0 ? "FAIL" : "PASS";
  console.log(`${state} ${result.path} HTTP ${result.status}`);
  for (const failure of result.failures) {
    console.log(`  - ${failure}`);
  }
}

if (failed.length > 0) {
  console.error(`Smoke failed for ${failed.length} route(s) at ${baseUrl}`);
  process.exit(1);
}

console.log(`Smoke passed for ${results.length} route(s) at ${baseUrl}`);
