from app.schemas import OutcomeReason, OutcomeReasonsResponse


def get_outcome_reasons() -> OutcomeReasonsResponse:
    return OutcomeReasonsResponse(
        version="2026-06-16",
        rules=[
            "outcome and reason are stored separately",
            "manual outcomes require an owner",
            "AI may propose an outcome but cannot close a deal without approval",
            "pre_win win is the only automatic entry point into execution funnel",
        ],
        reasons=[
            OutcomeReason(
                code="won",
                funnel="pre_win",
                title="Победили в процедуре",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Переход в post-win воронку разрешен только после протокола и handoff receipt.",
            ),
            OutcomeReason(
                code="lost_competition",
                funnel="pre_win",
                title="Проиграли в конкурентной борьбе",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Фиксируется отдельно от отказа и отмены заказчиком.",
            ),
            OutcomeReason(
                code="rejected_before_submission",
                funnel="pre_win",
                title="Отказались до подачи",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Нужна структурированная причина: риск, документы, сроки, поставщики или экономика.",
            ),
            OutcomeReason(
                code="deadline_expired",
                funnel="pre_win",
                title="Вышел срок",
                terminal=True,
                ai_can_suggest=False,
                requires_owner_approval=True,
                description="Автоправило может подсветить риск, но закрытие требует audit trail.",
            ),
            OutcomeReason(
                code="unprofitable",
                funnel="pre_win",
                title="Нерентабельная сделка",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Основание должно ссылаться на расчет экономики и коэффициенты организации.",
            ),
            OutcomeReason(
                code="cancelled_by_customer",
                funnel="pre_win",
                title="Отменена заказчиком",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=False,
                description="Не смешивается с проигрышем или ручным отказом.",
            ),
            OutcomeReason(
                code="manual_management",
                funnel="pre_win",
                title="Ручное управление",
                terminal=False,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Сделка остается живой, история и задачи не удаляются.",
            ),
            OutcomeReason(
                code="not_paid",
                funnel="execution",
                title="Не рассчитались",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Финал исполнения после победы, требует документов и владельца.",
            ),
            OutcomeReason(
                code="not_accepted",
                funnel="execution",
                title="Не приняли продукцию/результаты работы",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Отдельный финал исполнения, не равен проигрышу первой воронки.",
            ),
            OutcomeReason(
                code="penalties",
                funnel="execution",
                title="Штрафные санкции",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Фиксируется с основанием: договор, претензия, акт или расчет.",
            ),
            OutcomeReason(
                code="refund",
                funnel="execution",
                title="Возврат денежных средств",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Требует связки с платежами и закрывающими документами.",
            ),
            OutcomeReason(
                code="partial_payment",
                funnel="execution",
                title="Частичная оплата",
                terminal=True,
                ai_can_suggest=True,
                requires_owner_approval=True,
                description="Фиксирует отличие плановой и фактической экономики исполнения.",
            ),
        ],
    )
